### ISSUE TITLE
Request path for controller /metrics returns 404

### ISSUE THREAD

**Issue by bzon** [Stono/kconmon#13]
This is the deployment file:

```yaml
---
# Source: kconmon/templates/controller/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kconmon
    heritage: "Helm"
    release: "kconmon"
    chart: kconmon
  name: controller
  namespace: kconmon
spec:
  minReadySeconds: 15
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kconmon
      component: controller
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kconmon
        component: controller
    spec:
      terminationGracePeriodSeconds: 15
      dnsConfig:
        options:
        - name: ndots
          value: "1"
        searches:
        - monitoring.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      serviceAccountName: kconmon
      containers:
      - name: agent
        image: "stono/kconmon:0.4.3"
        imagePullPolicy: IfNotPresent
        args:
        - controller
        env:
        - name: CONTAINER_RESOURCE_REQUEST_MEMORY
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: requests.memory
        - name: CONTAINER_RESOURCE_LIMIT_MEMORY
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: DEPLOYMENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG
          value: "{\"dns\":{\"hosts\":[\"www.google.com\",\"kubernetes.default.svc.cluster.local\"],\"interval\":5000},\"failureDomainLabel\":\"failure-domain.beta.kubernetes.io/zone\",\"metricsPrefix\":\"kconmon\",\"nodeAntiAffinity\":[{\"key\":\"airflow\",\"value\":true}],\"port\":8080,\"tcp\":{\"interval\":5000,\"timeout\":1000},\"udp\":{\"interval\":5000,\"packets\":5,\"timeout\":250}}"
        ports:
        - name: http-web
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 1
          httpGet:
            path: /readiness
            port: 8080
        resources:
          requests:
            cpu: 50m
            memory: 80Mi
          limits:
            memory: 128Mi
```

Service.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kconmon
    heritage: "Helm"
    release: "kconmon"
    chart: kconmon
  name: controller
  namespace: kconmon
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: http-web
  selector:
    app: kconmon
    component: controller
  sessionAffinity: None
  type: ClusterIP
```
